### ISSUE TITLE
Create build integration script

### ISSUE THREAD

**Issue by stevenweaver** [veg/hyphy-gui#11]
We should have a `.travis.yml` script as part of this repo. datamonkey-js's `.travis.yml` script should require minimal adjustments if we'd like to use that as a template.

**Comment by stevenweaver** [comment]
[Link to datamonkey-js travis config](https://github.com/veg/datamonkey-js/blob/develop/.travis.yml)

**Comment by rdvelazquez** [comment]
Closed by #15
