### ISSUE TITLE
MPI for GARD

### ISSUE THREAD

**Issue by rdvelazquez** [veg/hyphy-gui#16]
GARD uses MPI. We can decide how we address this for the desktop app at a later date; I just wanted to log this as an issue so it doesn't get lost.

**Comment by stevenweaver** [comment]
`GARD.bf` just needs to be refactored to not be dependent on an MPI environment. `libv3` already has an abstraction available to detect MPI environments. GARD will not be supported by the desktop until it is refactored.

**Comment by spond** [comment]
Dear @rdvelazquez and @stevenweaver 

I concur that GARD needs to refactored to use the libv3 abstraction, and generally optimized. We could look at offering SBP on the desktop (which is simply a single-breakpoint version of GARD), and offer options to send GARD jobs to the cluster from the desktop app. Integration with the cluster would be a great selling point too.

Best,
Sergei

**Comment by rdvelazquez** [comment]
HyPhy 2.5 has a GARD implementation that doesn't need MPI.
