### ISSUE TITLE
Issues with installation

### ISSUE THREAD

**Issue by stephenshank** [veg/hyphy-gui#6]
@rdvelazquez experienced an issue during install:

[HyPhy-GUI_Error.txt](https://github.com/veg/hyphy-gui/files/1760171/HyPhy-GUI_Error.txt)

The issue seems to be related to building the MPI version of HyPhy. This needs to be fixed to develop analyses such as GARD.

**Comment by rdvelazquez** [comment]
This was addressed by adding MPI to the list of dependencies. (see: https://github.com/stephenshank/hyphy-gui/commit/d4f42e40f45acf3c4eeaa10e47f7b3ed8e79d546)
